HR/config/routes.rb
Rails.application.routes.draw do
  resources :resumes do
    resources :skills
    resources :languages
    resources :work_experiences
  end
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HR/app/models/language.rb
class Language < ApplicationRecord
  belongs_to :resume
end

HR/app/models/resume.rb
class Resume < ApplicationRecord
    has_many :skills, dependent: :destroy
    has_many :languages, dependent: :destroy
    has_many :work_experiences, dependent: :destroy 
end

HR/app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :resume
end

HR/app/models/work_experience.rb
class WorkExperience < ApplicationRecord
  belongs_to :resume
end

HR/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

HR/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
    
    def create
    @resume = Resume.find(params[:resume_id])
    @language = @resume.languages.create(language_params)
    redirect_to resume_path(@resume)
    end
 
  private
    def language_params
      params.require(:language).permit(:Title, :Level)
    end


end

HR/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy ]

  # GET /resumes or /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1 or /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes or /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully created." }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1 or /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to resume_url(@resume), notice: "Resume was successfully updated." }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1 or /resumes/1.json
  def destroy
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url, notice: "Resume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resume_params
      params.require(:resume).permit(:Name, :Image_Url, :Role, :Location, :Email, :Phone)
    end
end

HR/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def create
    @resume = Resume.find(params[:resume_id])
    @skill = @resume.skills.create(skill_params)
    redirect_to resume_path(@resume)
    end
 
  private
    def skill_params
      params.require(:skill).permit(:Title, :Level)
    end
end

HR/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

HR/app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
    def create
    @resume = Resume.find(params[:resume_id])
    @work_experiences = @resume.work_experiences.create(work_experience_params)
    redirect_to resume_path(@resume)
    end
 
  private
    def work_experience_params
      params.require(:work_experience).permit(:title, :education, :year_start, :year_end, :about)
    end
end

HR/app/helpers/application_helper.rb
module ApplicationHelper
end

HR/app/helpers/language_helper.rb
module LanguageHelper
end

HR/app/helpers/languages_helper.rb
module LanguagesHelper
end

HR/app/helpers/resumes_helper.rb
module ResumesHelper
end

HR/app/helpers/skills_helper.rb
module SkillsHelper
end

HR/app/helpers/welcome_helper.rb
module WelcomeHelper
end

HR/app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

HR/app/views/languages/_form.html.erb
<%= form_for([@resume, @resume.languages.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :Title %>
  </p>
  <p>
    <%= f.label :level %><br>
    <%= f.text_field :Level %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

HR/app/views/languages/_language.html.erb
<p>
  <strong>Title:</strong>
  <%= language.Title %>
</p>
 
<p>
  <strong>Level:</strong>
  <%= language.Level %>
</p>

HR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

HR/app/views/resumes/_form.html.erb
<%= form_for(resume) do |f| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Image_Url %>
    <%= f.text_field :Image_Url %>
  </div>

  <div class="field">
    <%= f.label :Role %>
    <%= f.text_field :Role %>
  </div>

  <div class="field">
    <%= f.label :Location %>
    <%= f.text_field :Location %>
  </div>

  <div class="field">
    <%= f.label :Email %>
    <%= f.text_field :Email %>
  </div>

  <div class="field">
    <%= f.label :Phone %>
    <%= f.text_field :Phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HR/app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

HR/app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Role</th>
      <th>Location</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.Name %></td>
        <td><%= resume.Image_Url %></td>
        <td><%= resume.Role %></td>
        <td><%= resume.Location %></td>
        <td><%= resume.Email %></td>
        <td><%= resume.Phone %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

HR/app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

HR/app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resume.Name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @resume.Image_Url %>
</p>

<p>
  <strong>Role:</strong>
  <%= @resume.Role %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resume.Location %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.Phone %>
</p>

<h2>Skills</h2>
<%= render @resume.skills %>

<h2>Add a Skill:</h2>
<%= render 'skills/form' %>

<h2>Languages</h2>
<%= render @resume.languages %>

<h2>Add a Language:</h2>
<%= render 'languages/form' %>

<h2>Work Experience</h2>
<%= render @resume.work_experiences %>

<h2>Add an Experience:</h2>
<%= render 'work_experiences/form' %>




<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>

HR/app/views/skills/_form.html.erb
<%= form_for([@resume, @resume.skills.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :Title %>
  </p>
  <p>
    <%= f.label :level %><br>
    <%= f.text_field :Level %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

HR/app/views/skills/_skill.html.erb
<p>
  <strong>Title:</strong>
  <%= skill.Title %>
</p>
 
<p>
  <strong>Level:</strong>
  <%= skill.Level %>
</p>

HR/app/views/welcome/index.html.erb
<h1>Your Resume Database</h1></h1>
<%= link_to 'My Resumes', controller: 'resumes' %>

HR/app/views/work_experiences/_form.html.erb
<%= form_for([@resume, @resume.work_experiences.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </p>
    <p>
    <%= f.label :year_start %><br>
    <%= f.text_field :year_start %>
  </p>
    <p>
    <%= f.label :year_end %><br>
    <%= f.text_field :year_end %>
  </p>
    <p>
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

HR/app/views/work_experiences/_work_experience.html.erb
<p>
  <strong>Title:</strong>
  <%= work_experience.title %>
</p>
 
<p>
  <strong>Website:</strong>
  <%= work_experience.education %>
</p>

<p>
  <strong>Year Start:</strong>
  <%= work_experience.year_start %>
</p>

<p>
  <strong>Year End:</strong>
  <%= work_experience.year_end %>
</p>

<p>
  <strong>About:</strong>
  <%= work_experience.about %>
</p>